apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nwxcuwp3o-go 
  janus-idp.io/tekton: nwxcuwp3o-go
  backstage.io/kubernetes-id: nwxcuwp3o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nwxcuwp3o-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml