apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nwxcuwp3o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nwxcuwp3o-go 
  name: nwxcuwp3o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nwxcuwp3o-go 
